Task9: Added initial implementation for time bound packets reading an…
Balvarezpandozi/ProjectCOSC4353 pull request #14
Opened 2022-10-17 04:59 UTC by atharvarajurkar

Task9: Added initial implementation for time bound packets reading and added methods to identify if packet uses IPv4 of IPv6 address. Added relevant junits as well.

2022-10-17 17:34 UTC, Balvarezpandozi commented
Other than the comments I added, everything else looks good to me. Let's discuss the issues you mentioned on discord after class. Then, we can fix them and merge this PR after refactoring. Great work!

2022-10-18 22:33 UTC, Balvarezpandozi requested changes

2022-10-18 22:56 UTC, atharvarajurkar commented on src/main/java/com/softwaredesign/Main.java
> +        System.out.println("Time Elapsed: " + stopwatch.getTime());
changes done

2022-10-19 16:16 UTC, Balvarezpandozi approved these changes

2022-10-19 16:16 UTC, merged